# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM java:8

LABEL MAINTAINER="cloud-sce-spotify@google.com"
LABEL Version="1.0"
ENV ORG_NUMBER orgnumber
ENV DATASET gce_capacity_log
ENV PROJECT_ID projectid
ENV OPERATION initial-vm-inventory

COPY gcpcapacitylog.jar gcpcapacitylog.jar
COPY run.sh run.sh
CMD ./run.sh