---
service_name:    prom
feature_name:    metrics
slo_name:        availability
slo_description: Valid HTTP code for > 99.9% of HTTP requests
slo_target:      0.999
backend:
  class:         Prometheus
  method:        query_sli
  url:           ${PROMETHEUS_URL}
  # Basic auth example:
  # headers:
  #   Content-Type: application/json
  #   Authorization: Basic b2s6cGFzcW==  # username:password base64-encoded
  measurement:
    expression:  >
      sum(rate(prometheus_http_requests_total{code=~"2..", handler="/metrics"}[window]))
      /
      sum(rate(prometheus_http_requests_total{handler="/metrics"}[window]))
exporters:
- class:         Prometheus
  url:           ${PROMETHEUS_PUSHGATEWAY_URL}
