---
service_name:     prom
feature_name:     metrics
slo_name:         availability
slo_description:  Valid HTTP code for > 99.9% of HTTP requests
slo_target:       0.999
backend:
  class:          Prometheus
  method:         good_bad_ratio
  url:            ${PROMETHEUS_URL}
  # Basic auth example:
  # headers:
  #   Content-Type: application/json
  #   Authorization: Basic b2s6cGFzcW==  # username:password base64-encoded
  measurement:
    filter_good:  prometheus_http_requests_total{code=~"2..", handler="/metrics"}[window]
    filter_valid: prometheus_http_requests_total{handler="/metrics"}[window]
    # filter_bad: prometheus_http_requests_total{code=~"5..", handler="/metrics"}[window]  # alternative to filter_valid field
exporters:
- class:          Prometheus
  url:            ${PROMETHEUS_PUSHGATEWAY_URL}
