trainingInput:
  scaleTier: STANDARD_1
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: auc_roc
    enableTrialEarlyStopping: True
    maxTrials: 400
    maxParallelTrials: 4
    params:
    - parameterName: dropout
      type: DOUBLE
      minValue: 0.0
      maxValue: 0.8
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: subspecies_embedding
      type: INTEGER
      minValue: 1
      maxValue: 250
      scaleType: UNIT_LOG_SCALE
    - parameterName: first_layer_size
      type: INTEGER
      minValue: 2
      maxValue: 1000
      scaleType: UNIT_LOG_SCALE
    - parameterName: layer_reduction_fraction
      type: DOUBLE
      minValue: 0.1
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: number_layers
      type: INTEGER
      minValue: 1
      maxValue: 20
      scaleType: UNIT_LOG_SCALE
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: batch_size
      type: DISCRETE
      discreteValues:
      - 8
      - 16
      - 32
      - 64
      scaleType: UNIT_LOG_SCALE
    - parameterName: tf_hub_module
      type: CATEGORICAL
      categoricalValues:
      - https://tfhub.dev/google/imagenet/inception_v1/feature_vector/1
      - https://tfhub.dev/google/imagenet/inception_v2/feature_vector/1
      - https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1
      - https://tfhub.dev/google/imagenet/mobilenet_v1_025_224/feature_vector/1
      - https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/2
      - https://tfhub.dev/google/imagenet/mobilenet_v2_035_224/feature_vector/2
      - https://tfhub.dev/google/imagenet/nasnet_mobile/feature_vector/1
      - https://tfhub.dev/google/imagenet/resnet_v1_50/feature_vector/1
      - https://tfhub.dev/google/imagenet/resnet_v1_152/feature_vector/1
      - https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/1
      - https://tfhub.dev/google/imagenet/resnet_v2_152/feature_vector/1