trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_m_p100
  hyperparameters:
    maxTrials: 100
    maxParallelTrials: 5
    enableTrialEarlyStopping: True
    goal: MAXIMIZE
    hyperparameterMetricTag: auc
    params:
    - parameterName: num_units
      type: INTEGER
      minValue: 8
      maxValue: 256
      scaleType: UNIT_LOG_SCALE
    - parameterName: embedding_dimension
      type: INTEGER
      discreteValues:
      minValue: 8
      maxValue: 1024
      scaleType: UNIT_LOG_SCALE
    - parameterName: num_hash_buckets
      type: INTEGER
      discreteValues:
      minValue: 10000
      maxValue: 50000
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
