trainingInput:
  scaleTier: STANDARD_1
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: mae
    enableTrialEarlyStopping: True
    maxTrials: 200
    maxParallelTrials: 4
    params:
    - parameterName: dropout
      type: DOUBLE
      minValue: 0.0
      maxValue: 0.8
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: hour_embedding
      type: INTEGER
      minValue: 1
      maxValue: 250
      scaleType: UNIT_LOG_SCALE
    - parameterName: day_embedding
      type: INTEGER
      minValue: 1
      maxValue: 250
      scaleType: UNIT_LOG_SCALE
    - parameterName: first_layer_size
      type: INTEGER
      minValue: 2
      maxValue: 1000
      scaleType: UNIT_LOG_SCALE
    - parameterName: layer_reduction_fraction
      type: DOUBLE
      minValue: 0.1
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: number_layers
      type: INTEGER
      minValue: 1
      maxValue: 20
      scaleType: UNIT_LOG_SCALE
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: batch_size
      type: DISCRETE
      discreteValues:
      - 16
      - 32
      - 64
      - 128
      - 256
      scaleType: UNIT_LOG_SCALE